import React, { useEffect, useState } from 'react';
import { useWorkspace } from '../context/WorkspaceContext';
import { tasks as tasksApi } from '../api';
import type {  Task  } from '../types';
import { CheckSquare, Clock, AlertCircle, CheckCircle2 } from 'lucide-react';
import toast from 'react-hot-toast';

const TasksPage: React.FC = () => {
  const { activeWorkspace } = useWorkspace();
  const [tasksList, setTasksList] = useState<Task[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchTasks = async () => {
    if (!activeWorkspace) return;
    setIsLoading(true);
    try {
      const data = await tasksApi.list(activeWorkspace.id);
      setTasksList(data);
    } catch (error) {
      toast.error('Failed to load tasks');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchTasks();
  }, [activeWorkspace]);

  const handleStatusChange = async (id: string, status: string) => {
    if (!activeWorkspace) return;
    try {
      await tasksApi.update(activeWorkspace.id, id, { status });
      setTasksList(tasksList.map(t => t.id === id ? { ...t, status: status as any } : t));
      toast.success('Task updated');
    } catch (error) {
      toast.error('Failed to update task');
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'COMPLETED': return <CheckCircle2 className="h-5 w-5 text-green-500" />;
      case 'IN_PROGRESS': return <Clock className="h-5 w-5 text-blue-500" />;
      case 'PENDING': return <AlertCircle className="h-5 w-5 text-yellow-500" />;
      default: return <AlertCircle className="h-5 w-5 text-gray-500" />;
    }
  };

  if (!activeWorkspace) {
    return (
      <div className="flex h-full items-center justify-center">
        <p className="text-gray-500">Please select a workspace.</p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl p-6">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">Tasks</h1>
        <p className="mt-1 text-sm text-gray-500">Tasks generated by the AI for this workspace.</p>
      </div>

      {isLoading ? (
        <div className="flex justify-center py-12">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent"></div>
        </div>
      ) : tasksList.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-lg border-2 border-dashed border-gray-300 py-16">
          <CheckSquare className="mb-4 h-12 w-12 text-gray-400" />
          <h3 className="text-lg font-medium text-gray-900">No tasks yet</h3>
          <p className="mb-6 mt-1 text-sm text-gray-500">Ask the AI to create tasks for you.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {tasksList.map((task) => (
            <div key={task.id} className="flex flex-col sm:flex-row items-start sm:items-center justify-between rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
              <div className="flex items-start space-x-4 mb-4 sm:mb-0">
                <div className="mt-0.5 flex-shrink-0">
                  {getStatusIcon(task.status)}
                </div>
                <div>
                  <h3 className={`text-base font-medium ${task.status === 'COMPLETED' ? 'text-gray-500 line-through' : 'text-gray-900'}`}>
                    {task.title}
                  </h3>
                  {task.description && (
                    <p className="mt-1 text-sm text-gray-600 max-w-2xl">{task.description}</p>
                  )}
                  {task.dueDate && (
                    <p className="mt-2 text-xs text-gray-500 flex items-center">
                      <Clock className="mr-1 h-3 w-3" /> Due: {new Date(task.dueDate).toLocaleDateString()}
                    </p>
                  )}
                </div>
              </div>
              <div className="flex-shrink-0 ml-10 sm:ml-4">
                <select
                  value={task.status}
                  onChange={(e) => handleStatusChange(task.id, e.target.value)}
                  className="block w-full rounded-md border-gray-300 py-1.5 pl-3 pr-10 text-sm focus:border-blue-500 focus:outline-none focus:ring-blue-500 border bg-gray-50"
                >
                  <option value="PENDING">Pending</option>
                  <option value="IN_PROGRESS">In Progress</option>
                  <option value="COMPLETED">Completed</option>
                  <option value="CANCELLED">Cancelled</option>
                </select>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default TasksPage;
